Soc
devlup-labs/woc pull request #22
Opened 2023-03-16 23:28 UTC by rohitkori

2023-03-16 23:35 UTC, RahulGopathi requested changes

2023-03-16 23:35 UTC, RahulGopathi commented on src/woc/settings.py
> +    # 'rest_framework.permissions.IsAuthenticated',
Redundant changes

2023-03-16 23:35 UTC, RahulGopathi commented on ui/src/components/CreateMentorProfile.vue
> +      console.log(localStorage)
remove all the console logs

2023-03-16 23:35 UTC, RahulGopathi commented on ui/src/router/middlewares/auth.js
> +    // }
remove all these comments

2023-03-17 10:07 UTC, RahulGopathi approved these changes

2023-03-17 10:46 UTC, rohitkori commented on ui/src/router/middlewares/auth.js
> +    // }
done

2023-03-17 10:46 UTC, rohitkori commented on ui/src/components/CreateMentorProfile.vue
> +      console.log(localStorage)
done

2023-03-17 10:48 UTC, RahulGopathi approved these changes

2023-03-17 10:48 UTC, merged